version: '3.8'

services:
  app:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine

volumes:
  mongo_data: